version: '3.1'

services:
  web:
    build: .
    container_name: phonetheria
    ports:
      - "8087:80"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=phone
      - POSTGRES_PASSWORD=phone
      - POSTGRES_DB=phonetheria

  db:
    image: postgres:latest
    container_name: db_phonetheria
    environment:
      POSTGRES_USER: phone
      POSTGRES_PASSWORD: phone
      POSTGRES_DB: phonetheria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  